name: quran__academy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/qa.png
    - assets/head.png
    - assets/buld.jpg
    - assets/map.png  
  
  fonts:
    - family: Tino  # Specify Tinos font family here
      fonts:
        - asset: assets/Tinos.ttf  # Path to the Tinos font file
   
  
