name: quran__academy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0  
  image_picker: ^1.1.2
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.2.3
  firebase_storage: ^12.2.0
  path_provider: ^2.1.4
  image: ^4.5.2
  flutter_credit_card: ^4.0.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/qa.png
    - assets/head.png
    - assets/buld.jpg
    - assets/map.png
    - assets/nasru.png
    - assets/About.jpg
    - assets/oth.jpg
    - assets/palli.jpg
    - assets/class.jpg
    - assets/gpphoto.jpg
    - assets/money.jpg
    - assets/spon.jpg
    - assets/prayer.jpg
    - assets/ann.jpg
      
  
  fonts:
    - family: Tino  # Specify Tinos font family here
      fonts:
        - asset: assets/Tinos.ttf  # Path to the Tinos font file
   
  
